// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef PublicKey AccountID;
//  ===========================================================================
class AccountID {
    var accountID: PublicKey? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedAccountID: AccountID) {
            PublicKey.encode(stream, encodedAccountID.accountID!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): AccountID {
            val decodedAccountID = AccountID()
            decodedAccountID.accountID = PublicKey.decode(stream)
            return decodedAccountID
        }
    }
}
