// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum AccountMergeResultCode
//  {
//      // codes considered as "success" for the operation
//      ACCOUNT_MERGE_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      ACCOUNT_MERGE_MALFORMED = -1,      // can't merge onto itself
//      ACCOUNT_MERGE_NO_ACCOUNT = -2,     // destination does not exist
//      ACCOUNT_MERGE_IMMUTABLE_SET = -3,  // source account has AUTH_IMMUTABLE set
//      ACCOUNT_MERGE_HAS_SUB_ENTRIES = -4 // account has trust lines/offers
//  };
//  ===========================================================================
enum class AccountMergeResultCode(val value: Int) {
    ACCOUNT_MERGE_SUCCESS(0),
    ACCOUNT_MERGE_MALFORMED(-1),
    ACCOUNT_MERGE_NO_ACCOUNT(-2),
    ACCOUNT_MERGE_IMMUTABLE_SET(-3),
    ACCOUNT_MERGE_HAS_SUB_ENTRIES(-4);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): AccountMergeResultCode {
            val value = stream.readInt()
            return when (value) {
                0 -> ACCOUNT_MERGE_SUCCESS
                -1 -> ACCOUNT_MERGE_MALFORMED
                -2 -> ACCOUNT_MERGE_NO_ACCOUNT
                -3 -> ACCOUNT_MERGE_IMMUTABLE_SET
                -4 -> ACCOUNT_MERGE_HAS_SUB_ENTRIES
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: AccountMergeResultCode) {
            stream.writeInt(value.value)
        }
    }

}
