// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum AllowTrustResultCode
//  {
//      // codes considered as "success" for the operation
//      ALLOW_TRUST_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      ALLOW_TRUST_MALFORMED = -1,     // asset is not ASSET_TYPE_ALPHANUM
//      ALLOW_TRUST_NO_TRUST_LINE = -2, // trustor does not have a trustline
//                                      // source account does not require trust
//      ALLOW_TRUST_TRUST_NOT_REQUIRED = -3,
//      ALLOW_TRUST_CANT_REVOKE = -4, // source account can't revoke trust,
//      ALLOW_TRUST_SELF_NOT_ALLOWED = -5 // trusting self is not allowed
//  };
//  ===========================================================================
enum class AllowTrustResultCode(val value: Int) {
    ALLOW_TRUST_SUCCESS(0),
    ALLOW_TRUST_MALFORMED(-1),
    ALLOW_TRUST_NO_TRUST_LINE(-2),
    ALLOW_TRUST_TRUST_NOT_REQUIRED(-3),
    ALLOW_TRUST_CANT_REVOKE(-4),
    ALLOW_TRUST_SELF_NOT_ALLOWED(-5);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): AllowTrustResultCode {
            val value = stream.readInt()
            return when (value) {
                0 -> ALLOW_TRUST_SUCCESS
                -1 -> ALLOW_TRUST_MALFORMED
                -2 -> ALLOW_TRUST_NO_TRUST_LINE
                -3 -> ALLOW_TRUST_TRUST_NOT_REQUIRED
                -4 -> ALLOW_TRUST_CANT_REVOKE
                -5 -> ALLOW_TRUST_SELF_NOT_ALLOWED
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: AllowTrustResultCode) {
            stream.writeInt(value.value)
        }
    }

}
