// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  union AllowTrustResult switch (AllowTrustResultCode code)
//  {
//  case ALLOW_TRUST_SUCCESS:
//      void;
//  default:
//      void;
//  };
//  ===========================================================================
class AllowTrustResult {
    var discriminant: AllowTrustResultCode? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedAllowTrustResult: AllowTrustResult
        ) {
            stream.writeInt(encodedAllowTrustResult.discriminant!!.value)
            when (encodedAllowTrustResult.discriminant) {
                AllowTrustResultCode.ALLOW_TRUST_SUCCESS -> {
                }
                else -> {
                }
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): AllowTrustResult {
            val decodedAllowTrustResult = AllowTrustResult()
            val discriminant = AllowTrustResultCode.decode(stream)
            decodedAllowTrustResult.discriminant = discriminant
            when (decodedAllowTrustResult.discriminant) {
                AllowTrustResultCode.ALLOW_TRUST_SUCCESS -> {
                }
                else -> {
                }
            }
            return decodedAllowTrustResult
        }
    }
}
