// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct Auth
//  {
//      // Empty message, just to confirm
//      // establishment of MAC keys.
//      int unused;
//  };
//  ===========================================================================
class Auth {
    var unused: Int? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedAuth: Auth) {
            stream.writeInt(encodedAuth.unused!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Auth {
            val decodedAuth = Auth()
            decodedAuth.unused = stream.readInt()
            return decodedAuth
        }
    }
}
