// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum BucketEntryType
//  {
//      LIVEENTRY = 0,
//      DEADENTRY = 1
//  };
//  ===========================================================================
enum class BucketEntryType(val value: Int) {
    LIVEENTRY(0),
    DEADENTRY(1);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): BucketEntryType {
            val value = stream.readInt()
            return when (value) {
                0 -> LIVEENTRY
                1 -> DEADENTRY
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: BucketEntryType) {
            stream.writeInt(value.value)
        }
    }

}
