// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct ChangeTrustOp
//  {
//      Asset line;
//
//      // if limit is set to 0, deletes the trust line
//      int64 limit;
//  };
//  ===========================================================================
class ChangeTrustOp {
    var line: Asset? = null
    var limit: Int64? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedChangeTrustOp: ChangeTrustOp) {
            Asset.encode(stream, encodedChangeTrustOp.line!!)
            Int64.encode(stream, encodedChangeTrustOp.limit!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): ChangeTrustOp {
            val decodedChangeTrustOp = ChangeTrustOp()
            decodedChangeTrustOp.line = Asset.decode(stream)
            decodedChangeTrustOp.limit = Int64.decode(stream)
            return decodedChangeTrustOp
        }
    }
}
