// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  union CreateAccountResult switch (CreateAccountResultCode code)
//  {
//  case CREATE_ACCOUNT_SUCCESS:
//      void;
//  default:
//      void;
//  };
//  ===========================================================================
class CreateAccountResult {
    var discriminant: CreateAccountResultCode? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedCreateAccountResult: CreateAccountResult
        ) {
            stream.writeInt(encodedCreateAccountResult.discriminant!!.value)
            when (encodedCreateAccountResult.discriminant) {
                CreateAccountResultCode.CREATE_ACCOUNT_SUCCESS -> {
                }
                else -> {
                }
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): CreateAccountResult {
            val decodedCreateAccountResult = CreateAccountResult()
            val discriminant = CreateAccountResultCode.decode(stream)
            decodedCreateAccountResult.discriminant = discriminant
            when (decodedCreateAccountResult.discriminant) {
                CreateAccountResultCode.CREATE_ACCOUNT_SUCCESS -> {
                }
                else -> {
                }
            }
            return decodedCreateAccountResult
        }
    }
}
