// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct CreateAccountOp
//  {
//      AccountID destination; // account to create
//      int64 startingBalance; // amount they end up with
//  };
//  ===========================================================================
class CreateAccountOp {
    var destination: AccountID? = null
    var startingBalance: Int64? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedCreateAccountOp: CreateAccountOp
        ) {
            AccountID.encode(stream, encodedCreateAccountOp.destination!!)
            Int64.encode(stream, encodedCreateAccountOp.startingBalance!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): CreateAccountOp {
            val decodedCreateAccountOp = CreateAccountOp()
            decodedCreateAccountOp.destination = AccountID.decode(stream)
            decodedCreateAccountOp.startingBalance = Int64.decode(stream)
            return decodedCreateAccountOp
        }
    }
}
