// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum CryptoKeyType
//  {
//      KEY_TYPE_ED25519 = 0,
//      KEY_TYPE_PRE_AUTH_TX = 1,
//      KEY_TYPE_HASH_X = 2
//  };
//  ===========================================================================
enum class CryptoKeyType(val value: Int) {
    KEY_TYPE_ED25519(0),
    KEY_TYPE_PRE_AUTH_TX(1),
    KEY_TYPE_HASH_X(2);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): CryptoKeyType {
            val value = stream.readInt()
            return when (value) {
                0 -> KEY_TYPE_ED25519
                1 -> KEY_TYPE_PRE_AUTH_TX
                2 -> KEY_TYPE_HASH_X
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: CryptoKeyType) {
            stream.writeInt(value.value)
        }
    }

}
