// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct Curve25519Public
//  {
//          opaque key[32];
//  };
//  ===========================================================================
class Curve25519Public {
    var key: ByteArray? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedCurve25519Public: Curve25519Public
        ) {
            val keysize = encodedCurve25519Public.key!!.size
            stream.write(encodedCurve25519Public.key!!, 0, keysize)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Curve25519Public {
            val decodedCurve25519Public = Curve25519Public()
            val keysize = 32
            decodedCurve25519Public.key = ByteArray(keysize)
            stream.read(decodedCurve25519Public.key!!, 0, keysize)
            return decodedCurve25519Public
        }
    }
}
