// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct Curve25519Secret
//  {
//          opaque key[32];
//  };
//  ===========================================================================
class Curve25519Secret {
    var key: ByteArray? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedCurve25519Secret: Curve25519Secret
        ) {
            val keysize = encodedCurve25519Secret.key!!.size
            stream.write(encodedCurve25519Secret.key!!, 0, keysize)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Curve25519Secret {
            val decodedCurve25519Secret = Curve25519Secret()
            val keysize = 32
            decodedCurve25519Secret.key = ByteArray(keysize)
            stream.read(decodedCurve25519Secret.key!!, 0, keysize)
            return decodedCurve25519Secret
        }
    }
}
