// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct DecoratedSignature
//  {
//      SignatureHint hint;  // last 4 bytes of the public key, used as a hint
//      Signature signature; // actual signature
//  };
//  ===========================================================================
class DecoratedSignature {
    var hint: SignatureHint? = null
    var signature: Signature? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedDecoratedSignature: DecoratedSignature
        ) {
            SignatureHint.encode(stream, encodedDecoratedSignature.hint!!)
            Signature.encode(stream, encodedDecoratedSignature.signature!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): DecoratedSignature {
            val decodedDecoratedSignature = DecoratedSignature()
            decodedDecoratedSignature.hint = SignatureHint.decode(stream)
            decodedDecoratedSignature.signature = Signature.decode(stream)
            return decodedDecoratedSignature
        }
    }
}
