// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct DontHave
//  {
//      MessageType type;
//      uint256 reqHash;
//  };
//  ===========================================================================
class DontHave {
    var type: MessageType? = null
    var reqHash: Uint256? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedDontHave: DontHave) {
            MessageType.encode(stream, encodedDontHave.type!!)
            Uint256.encode(stream, encodedDontHave.reqHash!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): DontHave {
            val decodedDontHave = DontHave()
            decodedDontHave.type = MessageType.decode(stream)
            decodedDontHave.reqHash = Uint256.decode(stream)
            return decodedDontHave
        }
    }
}
