// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum EnvelopeType
//  {
//      ENVELOPE_TYPE_SCP = 1,
//      ENVELOPE_TYPE_TX = 2,
//      ENVELOPE_TYPE_AUTH = 3
//  };
//  ===========================================================================
enum class EnvelopeType(val value: Int) {
    ENVELOPE_TYPE_SCP(1),
    ENVELOPE_TYPE_TX(2),
    ENVELOPE_TYPE_AUTH(3);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): EnvelopeType {
            return when (val value = stream.readInt()) {
                1 -> ENVELOPE_TYPE_SCP
                2 -> ENVELOPE_TYPE_TX
                3 -> ENVELOPE_TYPE_AUTH
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: EnvelopeType) {
            stream.writeInt(value.value)
        }
    }
}
