// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef opaque Hash[32];
//  ===========================================================================
class Hash {
    var hash: ByteArray? = null

    companion object {
        private const val hashsize = 32

        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedHash: Hash
        ) {
            val Hashsize = encodedHash.hash!!.size
            stream.write(encodedHash.hash!!, 0, Hashsize)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Hash {
            val decodedHash = Hash()
            decodedHash.hash = ByteArray(hashsize)
            stream.read(decodedHash.hash!!, 0, hashsize)
            return decodedHash
        }
    }
}
