// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct HmacSha256Mac
//  {
//          opaque mac[32];
//  };
//  ===========================================================================
class HmacSha256Mac {
    var mac: ByteArray? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedHmacSha256Mac: HmacSha256Mac) {
            val macsize = encodedHmacSha256Mac.mac!!.size
            stream.write(encodedHmacSha256Mac.mac!!, 0, macsize)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): HmacSha256Mac {
            val decodedHmacSha256Mac = HmacSha256Mac()
            val macsize = 32
            decodedHmacSha256Mac.mac = ByteArray(macsize)
            stream.read(decodedHmacSha256Mac.mac!!, 0, macsize)
            return decodedHmacSha256Mac
        }
    }
}
