// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct HmacSha256Key
//  {
//          opaque key[32];
//  };
//  ===========================================================================
class HmacSha256Key {
    var key: ByteArray? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedHmacSha256Key: HmacSha256Key) {
            val keysize = encodedHmacSha256Key.key!!.size
            stream.write(encodedHmacSha256Key.key!!, 0, keysize)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): HmacSha256Key {
            val decodedHmacSha256Key = HmacSha256Key()
            val keysize = 32
            decodedHmacSha256Key.key = ByteArray(keysize)
            stream.read(decodedHmacSha256Key.key!!, 0, keysize)
            return decodedHmacSha256Key
        }
    }
}
