// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum InflationResultCode
//  {
//      // codes considered as "success" for the operation
//      INFLATION_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      INFLATION_NOT_TIME = -1
//  };
//  ===========================================================================
enum class InflationResultCode(val value: Int) {
    INFLATION_SUCCESS(0),
    INFLATION_NOT_TIME(-1);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): InflationResultCode {
            val value = stream.readInt()
            return when (value) {
                0 -> INFLATION_SUCCESS
                -1 -> INFLATION_NOT_TIME
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: InflationResultCode) {
            stream.writeInt(value.value)
        }
    }
}
