// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef int int32;
//  ===========================================================================
class Int32 {
    var int32: Int? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedInt32: Int32) {
            stream.writeInt(encodedInt32.int32!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Int32 {
            val decodedInt32 = Int32()
            decodedInt32.int32 = stream.readInt()
            return decodedInt32
        }
    }
}
