// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef hyper int64;
//  ===========================================================================
class Int64 {
    var int64: Long? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedInt64: Int64) {
            stream.writeLong(encodedInt64.int64!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Int64 {
            val decodedInt64 = Int64()
            decodedInt64.int64 = stream.readLong()
            return decodedInt64
        }
    }
}
