// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum IPAddrType
//  {
//      IPv4 = 0,
//      IPv6 = 1
//  };
//  ===========================================================================
enum class IPAddrType(val value: Int) {
    IPv4(0),
    IPv6(1);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): IPAddrType {
            val value = stream.readInt()
            return when (value) {
                0 -> IPv4
                1 -> IPv6
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: IPAddrType) {
            stream.writeInt(value.value)
        }
    }

}
