// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef LedgerEntryChange LedgerEntryChanges<>;
//  ===========================================================================
class LedgerEntryChanges {
    var ledgerEntryChanges: Array<LedgerEntryChange?> = arrayOfNulls(0)

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedLedgerEntryChanges: LedgerEntryChanges
        ) {
            val LedgerEntryChangessize = encodedLedgerEntryChanges.ledgerEntryChanges.size
            stream.writeInt(LedgerEntryChangessize)
            for (i in 0 until LedgerEntryChangessize) {
                LedgerEntryChange.encode(
                    stream,
                    encodedLedgerEntryChanges.ledgerEntryChanges[i]!!
                )
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): LedgerEntryChanges {
            val decodedLedgerEntryChanges =
                LedgerEntryChanges()
            val LedgerEntryChangessize = stream.readInt()
            decodedLedgerEntryChanges.ledgerEntryChanges =
                arrayOfNulls(LedgerEntryChangessize)
            (0 until LedgerEntryChangessize).forEach { i ->
                decodedLedgerEntryChanges.ledgerEntryChanges[i] = LedgerEntryChange.decode(stream)
            }
            return decodedLedgerEntryChanges
        }
    }
}
