// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum LedgerEntryChangeType
//  {
//      LEDGER_ENTRY_CREATED = 0, // entry was added to the ledger
//      LEDGER_ENTRY_UPDATED = 1, // entry was modified in the ledger
//      LEDGER_ENTRY_REMOVED = 2, // entry was removed from the ledger
//      LEDGER_ENTRY_STATE = 3    // value of the entry
//  };
//  ===========================================================================
enum class LedgerEntryChangeType(val value: Int) {
    LEDGER_ENTRY_CREATED(0),
    LEDGER_ENTRY_UPDATED(1),
    LEDGER_ENTRY_REMOVED(2),
    LEDGER_ENTRY_STATE(3);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): LedgerEntryChangeType {
            val value = stream.readInt()
            return when (value) {
                0 -> LEDGER_ENTRY_CREATED
                1 -> LEDGER_ENTRY_UPDATED
                2 -> LEDGER_ENTRY_REMOVED
                3 -> LEDGER_ENTRY_STATE
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: LedgerEntryChangeType) {
            stream.writeInt(value.value)
        }
    }
}
