// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum LedgerEntryType
//  {
//      ACCOUNT = 0,
//      TRUSTLINE = 1,
//      OFFER = 2,
//      DATA = 3
//  };
//  ===========================================================================
enum class LedgerEntryType(val value: Int) {
    ACCOUNT(0),
    TRUSTLINE(1),
    OFFER(2),
    DATA(3);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): LedgerEntryType {
            return when (val value = stream.readInt()) {
                0 -> ACCOUNT
                1 -> TRUSTLINE
                2 -> OFFER
                3 -> DATA
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: LedgerEntryType) {
            stream.writeInt(value.value)
        }
    }
}
