// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  union ManageDataResult switch (ManageDataResultCode code)
//  {
//  case MANAGE_DATA_SUCCESS:
//      void;
//  default:
//      void;
//  };
//  ===========================================================================
class ManageDataResult {
    var discriminant: ManageDataResultCode? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedManageDataResult: ManageDataResult
        ) {
            stream.writeInt(encodedManageDataResult.discriminant!!.value)
            when (encodedManageDataResult.discriminant) {
                ManageDataResultCode.MANAGE_DATA_SUCCESS -> {
                }
                else -> {
                }
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): ManageDataResult {
            val decodedManageDataResult = ManageDataResult()
            val discriminant = ManageDataResultCode.decode(stream)
            decodedManageDataResult.discriminant = discriminant
            when (decodedManageDataResult.discriminant) {
                ManageDataResultCode.MANAGE_DATA_SUCCESS -> {
                }
                else -> {
                }
            }
            return decodedManageDataResult
        }
    }
}
