// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum ManageOfferResultCode
//  {
//      // codes considered as "success" for the operation
//      MANAGE_OFFER_SUCCESS = 0,
//
//      // codes considered as "failure" for the operation
//      MANAGE_OFFER_MALFORMED = -1,     // generated offer would be invalid
//      MANAGE_OFFER_SELL_NO_TRUST = -2, // no trust line for what we're selling
//      MANAGE_OFFER_BUY_NO_TRUST = -3,  // no trust line for what we're buying
//      MANAGE_OFFER_SELL_NOT_AUTHORIZED = -4, // not authorized to sell
//      MANAGE_OFFER_BUY_NOT_AUTHORIZED = -5,  // not authorized to buy
//      MANAGE_OFFER_LINE_FULL = -6,      // can't receive more of what it's buying
//      MANAGE_OFFER_UNDERFUNDED = -7,    // doesn't hold what it's trying to sell
//      MANAGE_OFFER_CROSS_SELF = -8,     // would cross an offer from the same user
//      MANAGE_OFFER_SELL_NO_ISSUER = -9, // no issuer for what we're selling
//      MANAGE_OFFER_BUY_NO_ISSUER = -10, // no issuer for what we're buying
//
//      // update errors
//      MANAGE_OFFER_NOT_FOUND = -11, // offerID does not match an existing offer
//
//      MANAGE_OFFER_LOW_RESERVE = -12 // not enough funds to create a new Offer
//  };
//  ===========================================================================
enum class ManageOfferResultCode(val value: Int) {
    MANAGE_OFFER_SUCCESS(0),
    MANAGE_OFFER_MALFORMED(-1),
    MANAGE_OFFER_SELL_NO_TRUST(-2),
    MANAGE_OFFER_BUY_NO_TRUST(-3),
    MANAGE_OFFER_SELL_NOT_AUTHORIZED(-4),
    MANAGE_OFFER_BUY_NOT_AUTHORIZED(-5),
    MANAGE_OFFER_LINE_FULL(-6),
    MANAGE_OFFER_UNDERFUNDED(-7),
    MANAGE_OFFER_CROSS_SELF(-8),
    MANAGE_OFFER_SELL_NO_ISSUER(-9),
    MANAGE_OFFER_BUY_NO_ISSUER(-10),
    MANAGE_OFFER_NOT_FOUND(-11),
    MANAGE_OFFER_LOW_RESERVE(-12);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): ManageOfferResultCode {
            val value = stream.readInt()
            return when (value) {
                0 -> MANAGE_OFFER_SUCCESS
                -1 -> MANAGE_OFFER_MALFORMED
                -2 -> MANAGE_OFFER_SELL_NO_TRUST
                -3 -> MANAGE_OFFER_BUY_NO_TRUST
                -4 -> MANAGE_OFFER_SELL_NOT_AUTHORIZED
                -5 -> MANAGE_OFFER_BUY_NOT_AUTHORIZED
                -6 -> MANAGE_OFFER_LINE_FULL
                -7 -> MANAGE_OFFER_UNDERFUNDED
                -8 -> MANAGE_OFFER_CROSS_SELF
                -9 -> MANAGE_OFFER_SELL_NO_ISSUER
                -10 -> MANAGE_OFFER_BUY_NO_ISSUER
                -11 -> MANAGE_OFFER_NOT_FOUND
                -12 -> MANAGE_OFFER_LOW_RESERVE
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: ManageOfferResultCode) {
            stream.writeInt(value.value)
        }
    }

}
