// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum ManageOfferEffect
//  {
//      MANAGE_OFFER_CREATED = 0,
//      MANAGE_OFFER_UPDATED = 1,
//      MANAGE_OFFER_DELETED = 2
//  };
//  ===========================================================================
enum class ManageOfferEffect(val value: Int) {
    MANAGE_OFFER_CREATED(0),
    MANAGE_OFFER_UPDATED(1),
    MANAGE_OFFER_DELETED(2);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): ManageOfferEffect {
            val value = stream.readInt()
            return when (value) {
                0 -> MANAGE_OFFER_CREATED
                1 -> MANAGE_OFFER_UPDATED
                2 -> MANAGE_OFFER_DELETED
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: ManageOfferEffect) {
            stream.writeInt(value.value)
        }
    }

}
