// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum MemoType
//  {
//      MEMO_NONE = 0,
//      MEMO_TEXT = 1,
//      MEMO_ID = 2,
//      MEMO_HASH = 3,
//      MEMO_RETURN = 4
//  };
//  ===========================================================================
enum class MemoType(val value: Int) {
    MEMO_NONE(0),
    MEMO_TEXT(1),
    MEMO_ID(2),
    MEMO_HASH(3),
    MEMO_RETURN(4);

    companion object {
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): MemoType {
            val value = stream.readInt()
            return when (value) {
                0 -> MEMO_NONE
                1 -> MEMO_TEXT
                2 -> MEMO_ID
                3 -> MEMO_HASH
                4 -> MEMO_RETURN
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: MemoType) {
            stream.writeInt(value.value)
        }
    }
}
