// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef PublicKey NodeID;
//  ===========================================================================
class NodeID {
    var NodeID: PublicKey? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedNodeID: NodeID) {
            PublicKey.encode(stream, encodedNodeID.NodeID!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): NodeID {
            val decodedNodeID = NodeID()
            decodedNodeID.NodeID = PublicKey.decode(stream)
            return decodedNodeID
        }
    }
}
