// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum OperationResultCode
//  {
//      opINNER = 0, // inner object result is valid
//
//      opBAD_AUTH = -1,  // too few valid signatures / wrong network
//      opNO_ACCOUNT = -2 // source account was not found
//  };
//  ===========================================================================
enum class OperationResultCode(val value: Int) {
    opINNER(0),
    opBAD_AUTH(-1),
    opNO_ACCOUNT(-2);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): OperationResultCode {
            val value = stream.readInt()
            return when (value) {
                0 -> opINNER
                -1 -> opBAD_AUTH
                -2 -> opNO_ACCOUNT
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: OperationResultCode) {
            stream.writeInt(value.value)
        }
    }
}
