// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum OperationType
//  {
//      CREATE_ACCOUNT = 0,
//      PAYMENT = 1,
//      PATH_PAYMENT = 2,
//      MANAGE_OFFER = 3,
//      CREATE_PASSIVE_OFFER = 4,
//      SET_OPTIONS = 5,
//      CHANGE_TRUST = 6,
//      ALLOW_TRUST = 7,
//      ACCOUNT_MERGE = 8,
//      INFLATION = 9,
//      MANAGE_DATA = 10
//  };
//  ===========================================================================
enum class OperationType(val value: Int) {
    CREATE_ACCOUNT(0),
    PAYMENT(1),
    PATH_PAYMENT(2),
    MANAGE_OFFER(3),
    CREATE_PASSIVE_OFFER(4),
    SET_OPTIONS(5),
    CHANGE_TRUST(6),
    ALLOW_TRUST(7),
    ACCOUNT_MERGE(8),
    INFLATION(9),
    MANAGE_DATA(10);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): OperationType {
            val value = stream.readInt()
            return when (value) {
                0 -> CREATE_ACCOUNT
                1 -> PAYMENT
                2 -> PATH_PAYMENT
                3 -> MANAGE_OFFER
                4 -> CREATE_PASSIVE_OFFER
                5 -> SET_OPTIONS
                6 -> CHANGE_TRUST
                7 -> ALLOW_TRUST
                8 -> ACCOUNT_MERGE
                9 -> INFLATION
                10 -> MANAGE_DATA
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: OperationType) {
            stream.writeInt(value.value)
        }
    }
}
