// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct OperationMeta
//  {
//      LedgerEntryChanges changes;
//  };
//  ===========================================================================
class OperationMeta {
    var changes: LedgerEntryChanges? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedOperationMeta: OperationMeta) {
            LedgerEntryChanges.encode(stream, encodedOperationMeta.changes!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): OperationMeta {
            val decodedOperationMeta = OperationMeta()
            decodedOperationMeta.changes = LedgerEntryChanges.decode(stream)
            return decodedOperationMeta
        }
    }
}
