// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum PathPaymentResultCode
//  {
//      // codes considered as "success" for the operation
//      PATH_PAYMENT_SUCCESS = 0, // success
//
//      // codes considered as "failure" for the operation
//      PATH_PAYMENT_MALFORMED = -1,          // bad input
//      PATH_PAYMENT_UNDERFUNDED = -2,        // not enough funds in source account
//      PATH_PAYMENT_SRC_NO_TRUST = -3,       // no trust line on source account
//      PATH_PAYMENT_SRC_NOT_AUTHORIZED = -4, // source not authorized to transfer
//      PATH_PAYMENT_NO_DESTINATION = -5,     // destination account does not exist
//      PATH_PAYMENT_NO_TRUST = -6,           // dest missing a trust line for asset
//      PATH_PAYMENT_NOT_AUTHORIZED = -7,     // dest not authorized to hold asset
//      PATH_PAYMENT_LINE_FULL = -8,          // dest would go above their limit
//      PATH_PAYMENT_NO_ISSUER = -9,          // missing issuer on one asset
//      PATH_PAYMENT_TOO_FEW_OFFERS = -10,    // not enough offers to satisfy path
//      PATH_PAYMENT_OFFER_CROSS_SELF = -11,  // would cross one of its own offers
//      PATH_PAYMENT_OVER_SENDMAX = -12       // could not satisfy sendmax
//  };
//  ===========================================================================
enum class PathPaymentResultCode(val value: Int) {
    PATH_PAYMENT_SUCCESS(0),
    PATH_PAYMENT_MALFORMED(-1),
    PATH_PAYMENT_UNDERFUNDED(-2),
    PATH_PAYMENT_SRC_NO_TRUST(-3),
    PATH_PAYMENT_SRC_NOT_AUTHORIZED(-4),
    PATH_PAYMENT_NO_DESTINATION(-5),
    PATH_PAYMENT_NO_TRUST(-6),
    PATH_PAYMENT_NOT_AUTHORIZED(-7),
    PATH_PAYMENT_LINE_FULL(-8),
    PATH_PAYMENT_NO_ISSUER(-9),
    PATH_PAYMENT_TOO_FEW_OFFERS(-10),
    PATH_PAYMENT_OFFER_CROSS_SELF(-11),
    PATH_PAYMENT_OVER_SENDMAX(-12);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): PathPaymentResultCode {
            val value = stream.readInt()
            return when (value) {
                0 -> PATH_PAYMENT_SUCCESS
                -1 -> PATH_PAYMENT_MALFORMED
                -2 -> PATH_PAYMENT_UNDERFUNDED
                -3 -> PATH_PAYMENT_SRC_NO_TRUST
                -4 -> PATH_PAYMENT_SRC_NOT_AUTHORIZED
                -5 -> PATH_PAYMENT_NO_DESTINATION
                -6 -> PATH_PAYMENT_NO_TRUST
                -7 -> PATH_PAYMENT_NOT_AUTHORIZED
                -8 -> PATH_PAYMENT_LINE_FULL
                -9 -> PATH_PAYMENT_NO_ISSUER
                -10 -> PATH_PAYMENT_TOO_FEW_OFFERS
                -11 -> PATH_PAYMENT_OFFER_CROSS_SELF
                -12 -> PATH_PAYMENT_OVER_SENDMAX
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: PathPaymentResultCode) {
            stream.writeInt(value.value)
        }
    }

}
