// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct PaymentOp
//  {
//      AccountID destination; // recipient of the payment
//      Asset asset;           // what they end up with
//      int64 amount;          // amount they end up with
//  };
//  ===========================================================================
class PaymentOp {
    var destination: AccountID? = null
    var asset: Asset? = null
    var amount: Int64? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedPaymentOp: PaymentOp) {
            AccountID.encode(stream, encodedPaymentOp.destination!!)
            Asset.encode(stream, encodedPaymentOp.asset!!)
            Int64.encode(stream, encodedPaymentOp.amount!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): PaymentOp {
            val decodedPaymentOp = PaymentOp()
            decodedPaymentOp.destination = AccountID.decode(stream)
            decodedPaymentOp.asset = Asset.decode(stream)
            decodedPaymentOp.amount = Int64.decode(stream)
            return decodedPaymentOp
        }
    }
}
