// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  union PaymentResult switch (PaymentResultCode code)
//  {
//  case PAYMENT_SUCCESS:
//      void;
//  default:
//      void;
//  };
//  ===========================================================================
class PaymentResult {
    var discriminant: PaymentResultCode? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedPaymentResult: PaymentResult) {
            stream.writeInt(encodedPaymentResult.discriminant!!.value)
            when (encodedPaymentResult.discriminant) {
                PaymentResultCode.PAYMENT_SUCCESS -> {
                }
                else -> {
                }
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): PaymentResult {
            val decodedPaymentResult = PaymentResult()
            val discriminant = PaymentResultCode.decode(stream)
            decodedPaymentResult.discriminant = discriminant
            when (decodedPaymentResult.discriminant) {
                PaymentResultCode.PAYMENT_SUCCESS -> {
                }
                else -> {
                }
            }
            return decodedPaymentResult
        }
    }
}
