// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum PublicKeyType
//  {
//      PUBLIC_KEY_TYPE_ED25519 = KEY_TYPE_ED25519
//  };
//  ===========================================================================
enum class PublicKeyType(val value: Int) {
    PUBLIC_KEY_TYPE_ED25519(0);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): PublicKeyType {
            val value = stream.readInt()
            return when (value) {
                0 -> PUBLIC_KEY_TYPE_ED25519
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: PublicKeyType) {
            stream.writeInt(value.value)
        }
    }

}
