// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  union PublicKey switch (PublicKeyType type)
//  {
//  case PUBLIC_KEY_TYPE_ED25519:
//      uint256 ed25519;
//  };
//  ===========================================================================
class PublicKey {
    var discriminant: PublicKeyType? = null
    var ed25519: Uint256? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedPublicKey: PublicKey
        ) {
            stream.writeInt(encodedPublicKey.discriminant!!.value)
            when (encodedPublicKey.discriminant) {
                PublicKeyType.PUBLIC_KEY_TYPE_ED25519 -> Uint256.encode(
                    stream,
                    encodedPublicKey.ed25519!!
                )
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): PublicKey {
            val decodedPublicKey = PublicKey()
            val discriminant = PublicKeyType.decode(stream)
            decodedPublicKey.discriminant = discriminant
            when (decodedPublicKey.discriminant) {
                PublicKeyType.PUBLIC_KEY_TYPE_ED25519 -> decodedPublicKey.ed25519 =
                    Uint256.decode(stream)
            }
            return decodedPublicKey
        }
    }
}
