// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct SCPEnvelope
//  {
//      SCPStatement statement;
//      Signature signature;
//  };
//  ===========================================================================
class SCPEnvelope {
    var statement: SCPStatement? = null
    var signature: Signature? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedSCPEnvelope: SCPEnvelope) {
            SCPStatement.encode(stream, encodedSCPEnvelope.statement!!)
            Signature.encode(stream, encodedSCPEnvelope.signature!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): SCPEnvelope {
            val decodedSCPEnvelope = SCPEnvelope()
            decodedSCPEnvelope.statement = SCPStatement.decode(stream)
            decodedSCPEnvelope.signature = Signature.decode(stream)
            return decodedSCPEnvelope
        }
    }
}
