// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  union SCPHistoryEntry switch (int v)
//  {
//  case 0:
//      SCPHistoryEntryV0 v0;
//  };
//  ===========================================================================
class SCPHistoryEntry {
    var discriminant: Int? = null
    var v0: SCPHistoryEntryV0? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedSCPHistoryEntry: SCPHistoryEntry
        ) {
            stream.writeInt(encodedSCPHistoryEntry.discriminant!!.toInt())
            when (encodedSCPHistoryEntry.discriminant) {
                0 -> SCPHistoryEntryV0.encode(stream, encodedSCPHistoryEntry.v0!!)
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): SCPHistoryEntry {
            val decodedSCPHistoryEntry = SCPHistoryEntry()
            val discriminant = stream.readInt()
            decodedSCPHistoryEntry.discriminant = discriminant
            when (decodedSCPHistoryEntry.discriminant) {
                0 -> decodedSCPHistoryEntry.v0 = SCPHistoryEntryV0.decode(stream)
            }
            return decodedSCPHistoryEntry
        }
    }
}
