// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum SCPStatementType
//  {
//      SCP_ST_PREPARE = 0,
//      SCP_ST_CONFIRM = 1,
//      SCP_ST_EXTERNALIZE = 2,
//      SCP_ST_NOMINATE = 3
//  };
//  ===========================================================================
enum class SCPStatementType(val value: Int) {
    SCP_ST_PREPARE(0),
    SCP_ST_CONFIRM(1),
    SCP_ST_EXTERNALIZE(2),
    SCP_ST_NOMINATE(3);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): SCPStatementType {
            val value = stream.readInt()
            return when (value) {
                0 -> SCP_ST_PREPARE
                1 -> SCP_ST_CONFIRM
                2 -> SCP_ST_EXTERNALIZE
                3 -> SCP_ST_NOMINATE
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: SCPStatementType) {
            stream.writeInt(value.value)
        }
    }
}
