// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef uint64 SequenceNumber;
//  ===========================================================================
class SequenceNumber {
    var sequenceNumber: Uint64? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedSequenceNumber: SequenceNumber
        ) {
            Uint64.encode(stream, encodedSequenceNumber.sequenceNumber!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): SequenceNumber {
            val decodedSequenceNumber = SequenceNumber()
            decodedSequenceNumber.sequenceNumber = Uint64.decode(stream)
            return decodedSequenceNumber
        }
    }
}
