// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  union SetOptionsResult switch (SetOptionsResultCode code)
//  {
//  case SET_OPTIONS_SUCCESS:
//      void;
//  default:
//      void;
//  };
//  ===========================================================================
class SetOptionsResult {
    var discriminant: SetOptionsResultCode? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedSetOptionsResult: SetOptionsResult
        ) {
            stream.writeInt(encodedSetOptionsResult.discriminant!!.value)
            when (encodedSetOptionsResult.discriminant) {
                SetOptionsResultCode.SET_OPTIONS_SUCCESS -> {
                }
                else -> {
                }
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): SetOptionsResult {
            val decodedSetOptionsResult = SetOptionsResult()
            val discriminant = SetOptionsResultCode.decode(stream)
            decodedSetOptionsResult.discriminant = discriminant
            when (decodedSetOptionsResult.discriminant) {
                SetOptionsResultCode.SET_OPTIONS_SUCCESS -> {
                }
                else -> {
                }
            }
            return decodedSetOptionsResult
        }
    }
}
