// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct Signer
//  {
//      SignerKey key;
//      uint32 weight; // really only need 1byte
//  };
//  ===========================================================================
class Signer {
    var key: SignerKey? = null
    var weight: Uint32? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedSigner: Signer
        ) {
            SignerKey.encode(stream, encodedSigner.key!!)
            Uint32.encode(stream, encodedSigner.weight!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Signer {
            val decodedSigner = Signer()
            decodedSigner.key = SignerKey.decode(stream)
            decodedSigner.weight = Uint32.decode(stream)
            return decodedSigner
        }
    }
}
