// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct SimplePaymentResult
//  {
//      AccountID destination;
//      Asset asset;
//      int64 amount;
//  };
//  ===========================================================================
class SimplePaymentResult {
    var destination: AccountID? = null
    var asset: Asset? = null
    var amount: Int64? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedSimplePaymentResult: SimplePaymentResult
        ) {
            AccountID.encode(stream, encodedSimplePaymentResult.destination!!)
            Asset.encode(stream, encodedSimplePaymentResult.asset!!)
            Int64.encode(stream, encodedSimplePaymentResult.amount!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): SimplePaymentResult {
            val decodedSimplePaymentResult = SimplePaymentResult()
            decodedSimplePaymentResult.destination = AccountID.decode(stream)
            decodedSimplePaymentResult.asset = Asset.decode(stream)
            decodedSimplePaymentResult.amount = Int64.decode(stream)
            return decodedSimplePaymentResult
        }
    }
}
