// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef string string64<64>;
//  ===========================================================================
class String64 {
    var string64: String? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedString64: String64) {
            stream.writeString(encodedString64.string64!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): String64 {
            val decodedString64 = String64()
            decodedString64.string64 = stream.readString()
            return decodedString64
        }
    }
}
