// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef opaque Thresholds[4];
//  ===========================================================================
class Thresholds {
    var thresholds: ByteArray? = null

    companion object {
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedThresholds: Thresholds
        ) {
            val Thresholdssize = encodedThresholds.thresholds!!.size
            stream.write(encodedThresholds.thresholds!!, 0, Thresholdssize)
        }

        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Thresholds {
            val decodedThresholds =
                Thresholds()
            val Thresholdssize = 4
            decodedThresholds.thresholds = ByteArray(Thresholdssize)
            stream.read(decodedThresholds.thresholds!!, 0, Thresholdssize)
            return decodedThresholds
        }
    }
}
