// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct TimeBounds
//  {
//      uint64 minTime;
//      uint64 maxTime; // 0 here means no maxTime
//  };
//  ===========================================================================
class TimeBounds {
    var minTime: Uint64? = null
    var maxTime: Uint64? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedTimeBounds: TimeBounds
        ) {
            Uint64.encode(stream, encodedTimeBounds.minTime!!)
            Uint64.encode(stream, encodedTimeBounds.maxTime!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): TimeBounds {
            val decodedTimeBounds = TimeBounds()
            decodedTimeBounds.minTime = Uint64.decode(stream)
            decodedTimeBounds.maxTime = Uint64.decode(stream)
            return decodedTimeBounds
        }
    }
}
