// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  struct TransactionResultSet
//  {
//      TransactionResultPair results<>;
//  };
//  ===========================================================================
class TransactionResultSet {
    var results: Array<TransactionResultPair?> = arrayOfNulls(0)

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedTransactionResultSet: TransactionResultSet
        ) {
            val resultssize = encodedTransactionResultSet.results.size
            stream.writeInt(resultssize)
            for (i in 0 until resultssize) {
                TransactionResultPair.encode(stream, encodedTransactionResultSet.results[i]!!)
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): TransactionResultSet {
            val decodedTransactionResultSet = TransactionResultSet()
            val resultssize = stream.readInt()
            decodedTransactionResultSet.results = arrayOfNulls(resultssize)
            for (i in 0 until resultssize) {
                decodedTransactionResultSet.results[i] = TransactionResultPair.decode(stream)
            }
            return decodedTransactionResultSet
        }
    }
}
