// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  enum TrustLineFlags
//  {
//      // issuer has authorized account to perform transactions with its credit
//      AUTHORIZED_FLAG = 1
//  };
//  ===========================================================================
enum class TrustLineFlags(val value: Int) {
    AUTHORIZED_FLAG(1);

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): TrustLineFlags {
            val value = stream.readInt()
            return when (value) {
                1 -> AUTHORIZED_FLAG
                else -> throw RuntimeException("Unknown enum value: $value")
            }
        }

        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, value: TrustLineFlags) {
            stream.writeInt(value.value)
        }
    }
}
