// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef unsigned int uint32;
//  ===========================================================================
class Uint32 {
    var uint32: Int? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedUint32: Uint32) {
            stream.writeInt(encodedUint32.uint32!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Uint32 {
            val decodedUint32 = Uint32()
            decodedUint32.uint32 = stream.readInt()
            return decodedUint32
        }
    }
}
