// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef unsigned hyper uint64;
//  ===========================================================================
class Uint64 {
    var uint64: Long? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedUint64: Uint64) {
            stream.writeLong(encodedUint64.uint64!!)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Uint64 {
            val decodedUint64 = Uint64()
            decodedUint64.uint64 = stream.readLong()
            return decodedUint64
        }
    }
}
