// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef opaque uint256[32];
//  ===========================================================================
class Uint256 {
    var uint256: ByteArray? = null

    companion object {
        @JvmStatic
        @Throws(IOException::class)
        fun encode(stream: XdrDataOutputStream, encodedUint256: Uint256) {
            val uint256size = encodedUint256.uint256!!.size
            stream.write(encodedUint256.uint256!!, 0, uint256size)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Uint256 {
            val decodedUint256 = Uint256()
            val uint256size = 32
            decodedUint256.uint256 = ByteArray(uint256size)
            stream.read(decodedUint256.uint256!!, 0, uint256size)
            return decodedUint256
        }
    }
}
