// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten
package org.kin.stellarfork.xdr

import java.io.IOException

// === xdr source ============================================================
//  typedef opaque Value<>;
//  ===========================================================================
class Value {
    var value: ByteArray? = null

    companion object {
        @Throws(IOException::class)
        fun encode(
            stream: XdrDataOutputStream,
            encodedValue: Value
        ) {
            val Valuesize = encodedValue.value!!.size
            stream.writeInt(Valuesize)
            stream.write(encodedValue.value!!, 0, Valuesize)
        }

        @Throws(IOException::class)
        fun decode(stream: XdrDataInputStream): Value {
            val decodedValue = Value()
            val Valuesize = stream.readInt()
            decodedValue.value = ByteArray(Valuesize)
            stream.read(decodedValue.value!!, 0, Valuesize)
            return decodedValue
        }
    }
}
